services:
  tasker-psql:
    container_name: tasker-db
    image: postgres:16.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB:       ${POSTGRES_DB_NAME}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql